
/* ***

tst_ass.sql: tables and assertions for "audit-findings" 

make sure to have EMP/DEPT from demobld ! 

examples of audit_definitions:
 - total_headcnt: count employees, applies to Total 
 - dept_headcnt: count employees of 1 dept, applies to Dept.
 - infractions: count infr per emp, applies to emp
 - crimrec: applies to EMP only, not to dept or total
 - nr_reports_to : sum of all emps under 1 manager
 - 
 -


notes, etc..
 - a select in an assertion could yield some information as to what/where caused error ? 

*** */

spool tst_ass

select * from v$version ; 

-- drop assertion before tables...  dependencies.

drop assertion a_ass1_fnd_at_wrong_level ;
drop table a_fnd ; 
drop table a_def ;                


-- define an audit-item,
-- the item will apply to Either Total, Dept, Emp (or all...)
create table a_def (
  id      number generated by default as identity primary key
, a_name  varchar2(32)   not null -- short name
, a_desc  varchar2(128)   -- descriptive
, a_lvl   varchar2(32)   not null 
, a_source varchar2(32)
, a_sql   varchar2(1024)   -- optional SQL to generate the data
, a_api   varchar2(1024)  -- optional API call to get the data
);

alter table a_def add constraint a_def_uk_name      unique ( a_name );
alter table a_def add constraint a_def_lvl_lov      check ( a_lvl in ( 'TOTAL', 'DEPT', 'EMP'   )) ;
alter table a_def add constraint a_def_source_lov   check ( a_source in ( 'API', 'SQL', 'OTHER'   )) ;


-- table with findings, results.. here is where the arc comes in
create table a_fnd (
  id          number generated by default as identity primary key
, a_def_id    number  not null -- fk to a_def
, deptno      number           -- fk-arc to dept
, empno       number           -- fk-arc to emp  only one or none of the fks allowed
, n_result    number
, vc_result   varchar2(128) 
);

-- fks to dept and emp
alter table a_fnd add (
constraint  a_fnd_fk_dept
  foreign key     (deptno)
  references dept (deptno)
  );

alter table a_fnd add (
constraint  a_fnd_fk_emp
  foreign key    (empno)
  references emp (empno)
  );

-- to parent audit item
alter table a_fnd add (
constraint  a_fnd_fk_def
  foreign key      (a_def_id)
  references a_def (      id)
  );

-- X-arc: check only one of dept/emp FKs can be used, other must be NULL
-- also allowed: both-null, signify that the defnition applies to Total
alter table a_fnd add constraint a_fnd_arc_empdept 
check (   (deptno is not null and empno is null) 
       or (empno is not null and deptno is null) 
       or (empno is null and deptno is null )
      );

/* 
an A_DEF defined for DEPT, is not allowed to have an FNDing at EMP level
and vice-versa
*/

-- Ta-Daaaa
create assertion a_ass1_fnd_at_wrong_level
check (
  not exists (
    select 'E_finding_at_D_level' as ass1_result
      from a_def ad
         , a_fnd af
     where ad.id = af.a_def_id            -- join to a_def
       and ( 
              (   ad.a_lvl = 'DEPT'       -- invalid combination.
              and af.empno is not null    -- Dept level finding with Emp-key
              ) 
           OR (   ad.a_lvl = 'EMP'
              and af.deptno is not null
              )
           )
  )
);

/* 
now define some audit-items. 
Later: add their ready-to-un sql stmtns.

note: using double-quotes bcse the q-quote didnt work on older sqlplus ??

*/

insert into a_def ( a_name, a_lvl, a_source, a_desc, a_sql  )
values (                'Total_headcount'
, 'TOTAL', 'SQL' 
, 'Total number of employees.'
, '   -- total employees... 
      -- just insert a def_id and a result, keep both FKs at NULL
      insert into a_fnd ( a_def_id, n_result ) 
      select ad.id, count (*) 
      from a_def  ad
         , emp     e
      where ad.a_name = ''Total_headcount''
      group by ad.id ; ' 
) ;

prompt .
prompt Total Headcount inserted...
prompt .

-- audit-item, headcount_p_dept, somthing per dept..
-- even simpler would be: no need to join in dname..
insert into a_def ( a_name, a_lvl, a_source, a_desc, a_sql  )
values (                'Headcount_p_dept'
, 'DEPT', 'SQL' 
, 'Number of employees per dept.'
, '   -- employees per dept.. a dept-level finding
      -- select deptno to point FK to dept
      insert into a_fnd ( a_def_id, deptno, n_result )
      select ad.id, deptno, count (*)
      from dept d, a_def  ad
      where ad.a_name = ''Headcount_p_dept''
      group by d.deptno , ad.id;
    ' 
) ;

prompt Headcount per dept inserted

-- something per emp
insert into a_def ( a_name, a_lvl, a_source, a_desc, a_sql  )
values (              'Pay_p_emp'
, 'EMP', 'SQL'
, 'pay per employee to verify.'
, 'select ename, empno, sal + nvl ( comm, 0) as payout from emp;' 
) ;

prompt Pay_per_emp Inserted

-- for the record: an invalid type
insert into a_def ( a_name, a_lvl, a_source, a_desc, a_sql  )
values ( 'invalid?'
, 'Wrong level for definition', 'SQL'
, 'wrong definition'
, 'select -1 from dual; ' 
) ;

prompt .
prompt Error above, was on purpose, check the check-constr...
prompt .

/* 
now try to insert findings in the fnd-table..
*/

-- total employees.., 
-- just insert a def_id and a result, keep both FKs at NULL
insert into a_fnd ( a_def_id, n_result ) 
select ad.id, count (*) 
from a_def  ad
   , emp     e
where ad.a_name =     'Total_headcount'
group by ad.id ;

-- employees per dept.. a dept-level finding
-- select deptno to point FK to dept
insert into a_fnd ( a_def_id, deptno, n_result ) 
select ad.id, deptno, count (*) 
from dept d, a_def  ad
where ad.a_name =     'Headcount_p_dept'
group by d.deptno , ad.id;

set echo on

-- but try to store that dept-level finding at emp-level... 
-- should give assert-error
-- note: we need valid empno, if we try insert d.deptno, we get the FK constraint, 
-- hence, an FK fires before Assertion (and that makes sense)
insert into a_fnd ( a_def_id, empno, n_result ) 
select ad.id
     , max(e.empno)
     , count (*) 
from emp e, dept d, a_def  ad
where ad.a_name =       'Headcount_p_dept'
  and e.deptno = d.deptno
group by ad.id;

set echo off

prompt .
prompt Error, on purpose, check the Assertion...
prompt .


-- now store some emp-level data: FK empno
-- pay per emp, first the happy flow.
insert into a_fnd ( a_def_id, empno, n_result ) 
select ad.id
     , e.empno
     , sal + nvl ( comm , 0 ) 
from a_def ad , emp e
where  1=1 -- no join required
  and ad.a_name = 'Pay_p_emp' ;


-- now pay-per-emp, trying to collect at total level.. error
-- 
insert into a_fnd ( a_def_id, deptno, n_result ) 
select ad.id
     , d.deptno 
     , avg ( sal + nvl ( comm , 0 ) )
from a_def ad , dept d, emp e
where  1=1 -- no join required
  and d.deptno = e.deptno
  and ad.a_name = 'Pay_p_emp' 
  group by ad.id, d.deptno;

prompt .
prompt Error, on purpose, check the Assertion...
prompt .



-- add a commit, so data is visible to other sessions...
commit ; 

spool off

